### ISSUE TITLE
Downgrade and flashing of patched firmware

### ISSUE THREAD

**Issue by Puzzlehead0** [amazfitbip/documentation#1]
Hi,
I want tested downgrade amazfit bip but i don't know waht is "compile Gadgetbridge from master and install".
I installed Gadgetbridge, open .gps and choice open with gadgetbridge and  gadgetbridge say "Element cannot be installed".

Where is the problem?

**Comment by francko76** [comment]
You must use version 0.20.2 for flashing firmware

**Comment by Puzzlehead0** [comment]
I don't find  it this version. :-(

**Comment by dpeddi** [comment]
https://github.com/Freeyourgadget/Gadgetbridge/blob/master/CHANGELOG.md

I think they will release within a couple of days
