### ISSUE TITLE
Problem with translated vi zh-cn2en.py

### ISSUE THREAD

**Issue by tomurbanowicz** [amazfitbip/documentation#2]
There is an issue with translate FW. 
After tranlsate via zh-cn2en.py and then translate RES file, the texts in main manu in the watch is not center, but with the big padding from the left. 
![margin](https://user-images.githubusercontent.com/31843138/30289801-9dbd67a8-972d-11e7-953f-8a123e61b542.jpg)

**Comment by dpeddi** [comment]
You need to patch the binary by changing the offset where the image is placed.
This is an unsupported operation.

**Comment by tomurbanowicz** [comment]
Where is it exactly in FW?
